version: 'build #{build}'

before_build:
  - git submodule update --init

build_script:
  - gradlew -PpublishMode build

after_build:
  - if %APPVEYOR_REPO_TAG%==true ( gradlew -PpublishMode -PBINTRAY_REPO=kotlin-native -PVERSION_SUFFIX publish )
    else ( gradlew -PpublishMode -PBINTRAY_REPO=kotlin-dev -PVERSION_SUFFIX=-dev publish )
  - copy libui\build\classes\kotlin\windows\main\libui-cinterop-libui.klib libui-windows.klib
  - copy libui\build\classes\kotlin\windows\main\libui.klib libui-ktx-windows.klib
  - 7z a libui-samples-windows.zip
         .\samples\controlgallery\build\bin\windows\releaseExecutable\controlgallery.exe
         .\samples\datetime\build\bin\windows\releaseExecutable\datetime.exe
         .\samples\drawtext\build\bin\windows\releaseExecutable\drawtext.exe
         .\samples\form\build\bin\windows\releaseExecutable\form.exe
         .\samples\hello\build\bin\windows\releaseExecutable\hello.exe
         .\samples\hello-ktx\build\bin\windows\releaseExecutable\hello-ktx.exe
         .\samples\histogram\build\bin\windows\releaseExecutable\histogram.exe
         .\samples\logo\build\bin\windows\releaseExecutable\logo.exe
         .\samples\table\build\bin\windows\releaseExecutable\table.exe
         .\samples\timer\build\bin\windows\releaseExecutable\timer.exe
  - 7z l libui-samples-windows.zip
  - copy libui\build\classes\kotlin\windows64\main\libui-cinterop-libui.klib libui-windows64.klib
  - copy libui\build\classes\kotlin\windows64\main\libui.klib libui-ktx-windows64.klib
  - 7z a libui-samples-windows64.zip
         .\samples\controlgallery\build\bin\windows64\releaseExecutable\controlgallery.exe
         .\samples\datetime\build\bin\windows64\releaseExecutable\datetime.exe
         .\samples\drawtext\build\bin\windows64\releaseExecutable\drawtext.exe
         .\samples\form\build\bin\windows64\releaseExecutable\form.exe
         .\samples\hello\build\bin\windows64\releaseExecutable\hello.exe
         .\samples\hello-ktx\build\bin\windows64\releaseExecutable\hello-ktx.exe
         .\samples\histogram\build\bin\windows64\releaseExecutable\histogram.exe
         .\samples\logo\build\bin\windows64\releaseExecutable\logo.exe
         .\samples\table\build\bin\windows64\releaseExecutable\table.exe
         .\samples\timer\build\bin\windows64\releaseExecutable\timer.exe
  - 7z l libui-samples-windows64.zip

artifacts:
  - path: libui-windows.klib
    name: interop
  - path: libui-ktx-windows.klib
    name: library
  - path: libui-samples-windows.zip
    name: samples
  - path: libui-windows64.klib
    name: interop64
  - path: libui-ktx-windows64.klib
    name: library64
  - path: libui-samples-windows64.zip
    name: samples64

deploy:
  provider: GitHub
  artifact: interop, library, samples, interop64, library64, samples64
  auth_token:
    secure: "2l/602m6FkqAB9TTIAkPX3Erfwg9jVTlf/Inmf2dWcbOrJJzK/WrCUIgY3B4ngly"
  on:
    appveyor_repo_tag: true

environment:
  BINTRAY_API_KEY:
    secure: BhHNDSz5XPW90PhX7c/e+t4A3nNPNtsauux+yE9Lzjf90YR4PDMdk1bKiTS7nW5X
